name: audio_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.24
  - librosa=0.10.0
  - scipy=1.10.0
  - matplotlib=3.7.0
  - pyqt=5.15  # Use a broader specification, which can help conda find compatible versions
  - mplcursors=0.5.1
  - pip:
    - pyqt5==5.15.6  # Use pip to install a specific PyQt5 version if needed
    - soundfile==0.11.0  # Use pip to ensure the right version of SoundFile
